exclude: '^(ArduinoRoboCar\.py|ArduinoRoboCar2\.py|ArduinoRoboCar3\.py|cv2detectColor2web\.py|server\.py)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
